#git_host git_repo git_key git_dir git_branch
- hosts: "{{ pb_hosts }}"
  # remote_user: root
  become: yes
  roles:
    - role: install_package 
      vars:
        package_name: git
    - role: git_repo_dep